### ISSUE TITLE
修正箇所一覧

### ISSUE THREAD

**Issue by TakTadano** [recursion-teamdev-blue/git-workshop#11]
とりあえず修正が必要な箇所まとめてみました。

- [x] ヘッダーの項目を修正(drink, sweet, food->menu等)
- [x] googlemapの位置修正
- [x] フォント統一
- [x] フッターテキストの位置修正
- [x] buttonのデザイン統一
- [x] aboutのイラスト部分にslider実装

**Comment by mi-aa** [comment]
確認しました。
Accessのところ、画面狭めると字が画面から出てしまうような気がしますが、
プレビューの仕方が悪いのかもしれません。
みなさんプレビューをするにはファイルをダウンロードされているのでしょうか..？
